{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a1d244a5-a987-43cf-9e1d-76aecb9d41e1",
   "metadata": {},
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "\n",
    "Note: Here Exception class refers to the base class for all the exceptions."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f26a0c87-0b29-4a38-854e-48627e55526e",
   "metadata": {},
   "source": [
    "Answer 1. We use the Exception class as the base class for creating custom exceptions in Python because it provides a standard way of handling errors and exceptions in a program.\n",
    "\n",
    "The Exception class is the base class for all the built-in exceptions in Python, and it provides a set of methods and attributes that can be used to handle and manage exceptions in a program. When we create a custom exception, we inherit from the Exception class, which means that our custom exception inherits all the methods and attributes of the Exception class.\n",
    "\n",
    "By using the Exception class as the base class, we can ensure that our custom exception is compatible with the existing exception handling mechanisms in Python. This means that we can catch and handle our custom exception using the same try-except blocks and other exception handling mechanisms that are used for built-in exceptions in Python.\n",
    "\n",
    "Furthermore, the Exception class provides a standard way of representing and reporting errors and exceptions in a program. By inheriting from the Exception class, our custom exception can also provide useful information about the error or exception that occurred, such as a message or traceback information.\n",
    "\n",
    "In summary, we use the Exception class as the base class for creating custom exceptions in Python because it provides a standard way of handling and managing exceptions, ensures compatibility with existing exception handling mechanisms, and allows us to provide useful information about the error or exception that occurred.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4cf684ef-d96b-4865-9ed0-1ce0f89c824e",
   "metadata": {},
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "145729f8-c258-41e9-afd8-ef60957ab96b",
   "metadata": {},
   "outputs": [],
   "source": [
    "def print_exception_hierarchy(exception_class, level=0):\n",
    "    \"\"\"Print the Python Exception Hierarchy\"\"\"\n",
    "    print(\"\\t\" * level + exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, level + 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e51f95e6-4c35-485c-8ea5-e1920c7e1bf6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "BaseException\n",
      "\tException\n",
      "\t\tTypeError\n",
      "\t\t\tFloatOperation\n",
      "\t\t\tMultipartConversionError\n",
      "\t\tStopAsyncIteration\n",
      "\t\tStopIteration\n",
      "\t\tImportError\n",
      "\t\t\tModuleNotFoundError\n",
      "\t\t\tZipImportError\n",
      "\t\tOSError\n",
      "\t\t\tConnectionError\n",
      "\t\t\t\tBrokenPipeError\n",
      "\t\t\t\tConnectionAbortedError\n",
      "\t\t\t\tConnectionRefusedError\n",
      "\t\t\t\tConnectionResetError\n",
      "\t\t\t\t\tRemoteDisconnected\n",
      "\t\t\tBlockingIOError\n",
      "\t\t\tChildProcessError\n",
      "\t\t\tFileExistsError\n",
      "\t\t\tFileNotFoundError\n",
      "\t\t\tIsADirectoryError\n",
      "\t\t\tNotADirectoryError\n",
      "\t\t\tInterruptedError\n",
      "\t\t\t\tInterruptedSystemCall\n",
      "\t\t\tPermissionError\n",
      "\t\t\tProcessLookupError\n",
      "\t\t\tTimeoutError\n",
      "\t\t\tUnsupportedOperation\n",
      "\t\t\titimer_error\n",
      "\t\t\therror\n",
      "\t\t\tgaierror\n",
      "\t\t\tSSLError\n",
      "\t\t\t\tSSLCertVerificationError\n",
      "\t\t\t\tSSLZeroReturnError\n",
      "\t\t\t\tSSLWantWriteError\n",
      "\t\t\t\tSSLWantReadError\n",
      "\t\t\t\tSSLSyscallError\n",
      "\t\t\t\tSSLEOFError\n",
      "\t\t\tError\n",
      "\t\t\t\tSameFileError\n",
      "\t\t\tSpecialFileError\n",
      "\t\t\tExecError\n",
      "\t\t\tReadError\n",
      "\t\t\tURLError\n",
      "\t\t\t\tHTTPError\n",
      "\t\t\t\tContentTooShortError\n",
      "\t\t\tBadGzipFile\n",
      "\t\tEOFError\n",
      "\t\t\tIncompleteReadError\n",
      "\t\tRuntimeError\n",
      "\t\t\tRecursionError\n",
      "\t\t\tNotImplementedError\n",
      "\t\t\t\tZMQVersionError\n",
      "\t\t\t\tStdinNotImplementedError\n",
      "\t\t\t_DeadlockError\n",
      "\t\t\tBrokenBarrierError\n",
      "\t\t\tBrokenExecutor\n",
      "\t\t\t\tBrokenThreadPool\n",
      "\t\t\tSendfileNotAvailableError\n",
      "\t\t\tExtractionError\n",
      "\t\t\tVariableError\n",
      "\t\tNameError\n",
      "\t\t\tUnboundLocalError\n",
      "\t\tAttributeError\n",
      "\t\t\tFrozenInstanceError\n",
      "\t\tSyntaxError\n",
      "\t\t\tIndentationError\n",
      "\t\t\t\tTabError\n",
      "\t\tLookupError\n",
      "\t\t\tIndexError\n",
      "\t\t\tKeyError\n",
      "\t\t\t\tNoSuchKernel\n",
      "\t\t\t\tUnknownBackend\n",
      "\t\t\tCodecRegistryError\n",
      "\t\tValueError\n",
      "\t\t\tUnicodeError\n",
      "\t\t\t\tUnicodeEncodeError\n",
      "\t\t\t\tUnicodeDecodeError\n",
      "\t\t\t\tUnicodeTranslateError\n",
      "\t\t\tUnsupportedOperation\n",
      "\t\t\tJSONDecodeError\n",
      "\t\t\tSSLCertVerificationError\n",
      "\t\t\tError\n",
      "\t\t\tUnsupportedDigestmodError\n",
      "\t\t\tIllegalMonthError\n",
      "\t\t\tIllegalWeekdayError\n",
      "\t\t\tParserError\n",
      "\t\t\tClassNotFound\n",
      "\t\t\tClipboardEmpty\n",
      "\t\t\tMessageDefect\n",
      "\t\t\t\tNoBoundaryInMultipartDefect\n",
      "\t\t\t\tStartBoundaryNotFoundDefect\n",
      "\t\t\t\tCloseBoundaryNotFoundDefect\n",
      "\t\t\t\tFirstHeaderLineIsContinuationDefect\n",
      "\t\t\t\tMisplacedEnvelopeHeaderDefect\n",
      "\t\t\t\tMissingHeaderBodySeparatorDefect\n",
      "\t\t\t\tMultipartInvariantViolationDefect\n",
      "\t\t\t\tInvalidMultipartContentTransferEncodingDefect\n",
      "\t\t\t\tUndecodableBytesDefect\n",
      "\t\t\t\tInvalidBase64PaddingDefect\n",
      "\t\t\t\tInvalidBase64CharactersDefect\n",
      "\t\t\t\tInvalidBase64LengthDefect\n",
      "\t\t\t\tHeaderDefect\n",
      "\t\t\t\t\tInvalidHeaderDefect\n",
      "\t\t\t\t\tHeaderMissingRequiredValue\n",
      "\t\t\t\t\tNonPrintableDefect\n",
      "\t\t\t\t\tObsoleteHeaderDefect\n",
      "\t\t\t\t\tNonASCIILocalPartDefect\n",
      "\t\t\t\t\tInvalidDateDefect\n",
      "\t\t\tMacroToEdit\n",
      "\t\t\tInvalidFileException\n",
      "\t\t\tUnequalIterablesError\n",
      "\t\t\tInvalidVersion\n",
      "\t\t\t_InvalidELFFileHeader\n",
      "\t\t\tInvalidWheelFilename\n",
      "\t\t\tInvalidSdistFilename\n",
      "\t\t\tInvalidSpecifier\n",
      "\t\t\tInvalidMarker\n",
      "\t\t\tUndefinedComparison\n",
      "\t\t\tUndefinedEnvironmentName\n",
      "\t\t\tInvalidRequirement\n",
      "\t\t\t\tRequirementParseError\n",
      "\t\t\tInvalidVersion\n",
      "\t\tAssertionError\n",
      "\t\tArithmeticError\n",
      "\t\t\tFloatingPointError\n",
      "\t\t\tOverflowError\n",
      "\t\t\tZeroDivisionError\n",
      "\t\t\t\tDivisionByZero\n",
      "\t\t\t\tDivisionUndefined\n",
      "\t\t\tDecimalException\n",
      "\t\t\t\tClamped\n",
      "\t\t\t\tRounded\n",
      "\t\t\t\t\tUnderflow\n",
      "\t\t\t\t\tOverflow\n",
      "\t\t\t\tInexact\n",
      "\t\t\t\t\tUnderflow\n",
      "\t\t\t\t\tOverflow\n",
      "\t\t\t\tSubnormal\n",
      "\t\t\t\t\tUnderflow\n",
      "\t\t\t\tDivisionByZero\n",
      "\t\t\t\tFloatOperation\n",
      "\t\t\t\tInvalidOperation\n",
      "\t\t\t\t\tConversionSyntax\n",
      "\t\t\t\t\tDivisionImpossible\n",
      "\t\t\t\t\tDivisionUndefined\n",
      "\t\t\t\t\tInvalidContext\n",
      "\t\tSystemError\n",
      "\t\t\tCodecRegistryError\n",
      "\t\tReferenceError\n",
      "\t\tMemoryError\n",
      "\t\tBufferError\n",
      "\t\tWarning\n",
      "\t\t\tUserWarning\n",
      "\t\t\t\tGetPassWarning\n",
      "\t\t\t\tFormatterWarning\n",
      "\t\t\tEncodingWarning\n",
      "\t\t\tDeprecationWarning\n",
      "\t\t\t\tProvisionalWarning\n",
      "\t\t\tPendingDeprecationWarning\n",
      "\t\t\tSyntaxWarning\n",
      "\t\t\tRuntimeWarning\n",
      "\t\t\t\tProactorSelectorThreadWarning\n",
      "\t\t\t\tUnknownTimezoneWarning\n",
      "\t\t\t\tPEP440Warning\n",
      "\t\t\tFutureWarning\n",
      "\t\t\t\tProvisionalCompleterWarning\n",
      "\t\t\tImportWarning\n",
      "\t\t\tUnicodeWarning\n",
      "\t\t\tBytesWarning\n",
      "\t\t\tResourceWarning\n",
      "\t\t\tDeprecatedTzFormatWarning\n",
      "\t\t\tPkgResourcesDeprecationWarning\n",
      "\t\t_OptionError\n",
      "\t\t_Error\n",
      "\t\terror\n",
      "\t\tVerbose\n",
      "\t\tError\n",
      "\t\tSubprocessError\n",
      "\t\t\tCalledProcessError\n",
      "\t\t\tTimeoutExpired\n",
      "\t\tTokenError\n",
      "\t\tStopTokenizing\n",
      "\t\tClassFoundException\n",
      "\t\tEndOfBlock\n",
      "\t\tTraitError\n",
      "\t\tError\n",
      "\t\tError\n",
      "\t\t\tCancelledError\n",
      "\t\t\tTimeoutError\n",
      "\t\t\tInvalidStateError\n",
      "\t\t_GiveupOnSendfile\n",
      "\t\terror\n",
      "\t\tIncomplete\n",
      "\t\tTimeoutError\n",
      "\t\tInvalidStateError\n",
      "\t\tLimitOverrunError\n",
      "\t\tQueueEmpty\n",
      "\t\tQueueFull\n",
      "\t\tEmpty\n",
      "\t\tFull\n",
      "\t\tArgumentError\n",
      "\t\tZMQBaseError\n",
      "\t\t\tZMQError\n",
      "\t\t\t\tContextTerminated\n",
      "\t\t\t\tAgain\n",
      "\t\t\t\tInterruptedSystemCall\n",
      "\t\t\tZMQBindError\n",
      "\t\t\tNotDone\n",
      "\t\tPickleError\n",
      "\t\t\tPicklingError\n",
      "\t\t\tUnpicklingError\n",
      "\t\t_Stop\n",
      "\t\tArgumentError\n",
      "\t\tArgumentTypeError\n",
      "\t\tConfigError\n",
      "\t\t\tConfigLoaderError\n",
      "\t\t\t\tArgumentError\n",
      "\t\t\tConfigFileNotFound\n",
      "\t\tConfigurableError\n",
      "\t\t\tMultipleInstanceError\n",
      "\t\tApplicationError\n",
      "\t\terror\n",
      "\t\tTimeoutError\n",
      "\t\terror\n",
      "\t\tReturnValueIgnoredError\n",
      "\t\tKeyReuseError\n",
      "\t\tUnknownKeyError\n",
      "\t\tLeakedCallbackError\n",
      "\t\tBadYieldError\n",
      "\t\tReturnValueIgnoredError\n",
      "\t\tReturn\n",
      "\t\tInvalidPortNumber\n",
      "\t\terror\n",
      "\t\tLZMAError\n",
      "\t\tRegistryError\n",
      "\t\t_GiveupOnFastCopy\n",
      "\t\tError\n",
      "\t\t\tNoSectionError\n",
      "\t\t\tDuplicateSectionError\n",
      "\t\t\tDuplicateOptionError\n",
      "\t\t\tNoOptionError\n",
      "\t\t\tInterpolationError\n",
      "\t\t\t\tInterpolationMissingOptionError\n",
      "\t\t\t\tInterpolationSyntaxError\n",
      "\t\t\t\tInterpolationDepthError\n",
      "\t\t\tParsingError\n",
      "\t\t\t\tMissingSectionHeaderError\n",
      "\t\tNoIPAddresses\n",
      "\t\tBadZipFile\n",
      "\t\tLargeZipFile\n",
      "\t\tBadEntryPoint\n",
      "\t\tNoSuchEntryPoint\n",
      "\t\tDuplicateKernelError\n",
      "\t\tErrorDuringImport\n",
      "\t\tNotOneValueFound\n",
      "\t\tCannotEval\n",
      "\t\tOptionError\n",
      "\t\tBdbQuit\n",
      "\t\tRestart\n",
      "\t\tExceptionPexpect\n",
      "\t\t\tEOF\n",
      "\t\t\tTIMEOUT\n",
      "\t\tPtyProcessError\n",
      "\t\tFindCmdError\n",
      "\t\tHomeDirError\n",
      "\t\tProfileDirError\n",
      "\t\tIPythonCoreError\n",
      "\t\t\tTryNext\n",
      "\t\t\tUsageError\n",
      "\t\t\tStdinNotImplementedError\n",
      "\t\tInputRejected\n",
      "\t\tGetoptError\n",
      "\t\tErrorToken\n",
      "\t\tPrefilterError\n",
      "\t\tAliasError\n",
      "\t\t\tInvalidAliasError\n",
      "\t\tError\n",
      "\t\t\tInterfaceError\n",
      "\t\t\tDatabaseError\n",
      "\t\t\t\tInternalError\n",
      "\t\t\t\tOperationalError\n",
      "\t\t\t\tProgrammingError\n",
      "\t\t\t\tIntegrityError\n",
      "\t\t\t\tDataError\n",
      "\t\t\t\tNotSupportedError\n",
      "\t\tWarning\n",
      "\t\tSpaceInInput\n",
      "\t\tDOMException\n",
      "\t\t\tIndexSizeErr\n",
      "\t\t\tDomstringSizeErr\n",
      "\t\t\tHierarchyRequestErr\n",
      "\t\t\tWrongDocumentErr\n",
      "\t\t\tInvalidCharacterErr\n",
      "\t\t\tNoDataAllowedErr\n",
      "\t\t\tNoModificationAllowedErr\n",
      "\t\t\tNotFoundErr\n",
      "\t\t\tNotSupportedErr\n",
      "\t\t\tInuseAttributeErr\n",
      "\t\t\tInvalidStateErr\n",
      "\t\t\tSyntaxErr\n",
      "\t\t\tInvalidModificationErr\n",
      "\t\t\tNamespaceErr\n",
      "\t\t\tInvalidAccessErr\n",
      "\t\t\tValidationErr\n",
      "\t\tValidationError\n",
      "\t\tEditReadOnlyBuffer\n",
      "\t\t_Retry\n",
      "\t\tInvalidLayoutError\n",
      "\t\tHeightIsUnknownError\n",
      "\t\tParserSyntaxError\n",
      "\t\tInternalParseError\n",
      "\t\t_PositionUpdatingFinished\n",
      "\t\tSimpleGetItemNotFound\n",
      "\t\tUncaughtAttributeError\n",
      "\t\tHasNoContext\n",
      "\t\tParamIssue\n",
      "\t\t_JediError\n",
      "\t\t\tInternalError\n",
      "\t\t\tWrongVersion\n",
      "\t\t\tRefactoringError\n",
      "\t\tOnErrorLeaf\n",
      "\t\tInvalidPythonEnvironment\n",
      "\t\tMessageError\n",
      "\t\t\tMessageParseError\n",
      "\t\t\t\tHeaderParseError\n",
      "\t\t\t\tBoundaryError\n",
      "\t\t\tMultipartConversionError\n",
      "\t\t\tCharsetError\n",
      "\t\tError\n",
      "\t\tHTTPException\n",
      "\t\t\tNotConnected\n",
      "\t\t\tInvalidURL\n",
      "\t\t\tUnknownProtocol\n",
      "\t\t\tUnknownTransferEncoding\n",
      "\t\t\tUnimplementedFileMode\n",
      "\t\t\tIncompleteRead\n",
      "\t\t\tImproperConnectionState\n",
      "\t\t\t\tCannotSendRequest\n",
      "\t\t\t\tCannotSendHeader\n",
      "\t\t\t\tResponseNotReady\n",
      "\t\t\tBadStatusLine\n",
      "\t\t\t\tRemoteDisconnected\n",
      "\t\t\tLineTooLong\n",
      "\t\tInteractivelyDefined\n",
      "\t\tKillEmbedded\n",
      "\t\tError\n",
      "\t\t\tNoSuchProcess\n",
      "\t\t\t\tZombieProcess\n",
      "\t\t\tAccessDenied\n",
      "\t\t\tTimeoutExpired\n",
      "\t\t_Ipv6UnsupportedError\n",
      "\t\tQueueEmpty\n",
      "\t\tQueueFull\n",
      "\t\tDebuggerInitializationError\n",
      "\t\tExpatError\n",
      "\t\tError\n",
      "\t\t\tProtocolError\n",
      "\t\t\tResponseError\n",
      "\t\t\tFault\n",
      "\t\tParseBaseException\n",
      "\t\t\tParseException\n",
      "\t\t\tParseFatalException\n",
      "\t\t\t\tParseSyntaxException\n",
      "\t\tRecursiveGrammarException\n",
      "\t\tResolutionError\n",
      "\t\t\tVersionConflict\n",
      "\t\t\t\tContextualVersionConflict\n",
      "\t\t\tDistributionNotFound\n",
      "\t\t\tUnknownExtra\n",
      "\t\t_Error\n",
      "\t\tUnableToResolveVariableException\n",
      "\t\tInvalidTypeInArgsException\n",
      "\tGeneratorExit\n",
      "\tSystemExit\n",
      "\tKeyboardInterrupt\n",
      "\tCancelledError\n",
      "\tAbortThread\n"
     ]
    }
   ],
   "source": [
    "print_exception_hierarchy(BaseException)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "11bc80c9-5a81-49d5-88cb-945dce5753bf",
   "metadata": {},
   "source": [
    "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cac34d1d-1a10-42fe-b4dc-565882c686a8",
   "metadata": {},
   "source": [
    "Answer 3. ArithmeticError is a built-in Python class that serves as the base class for any error that occurs during arithmetic operations. The errors defined in the ArithmeticError class are related to arithmetic operations and include:\n",
    "\n",
    "1. ZeroDivisionError - This error is raised when an attempt is made to divide a number by zero.\n",
    "\n",
    "Example. Mentioned below in the cell"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "5abe22f0-d418-491f-b1e3-3891b7b97f70",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Division by zero\n"
     ]
    }
   ],
   "source": [
    "x = 5 \n",
    "y = 0\n",
    "\n",
    "try:\n",
    "    result = x/y\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Division by zero\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "da85ff84-6948-4ddd-8e6b-37fbc55cf67c",
   "metadata": {},
   "source": [
    "2. OverflowError: This error is raised when the result of an arithmetic operation is too large to be represented by the data type used for the calculation.\n",
    "\n",
    "Example: "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "5bb56f17-0bb2-490d-9601-2ad551ae10b0",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "\n",
    "x = sys.maxsize\n",
    "y = sys.maxsize\n",
    "\n",
    "try:\n",
    "    result = x*y\n",
    "except OverflowError:\n",
    "    print(\"Error: integer OverFlow\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5d70b0af-fc68-4b41-88fc-45a9e9b8de28",
   "metadata": {},
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d9be2a95-bc6a-4a1b-88f1-59281d6dd387",
   "metadata": {},
   "source": [
    "Answer 5. The LookupError class is used in Python to handle errors that occur when a lookup operation fails. It is a base class for several other error classes that are used for more specific lookup-related errors, including KeyError and IndexError.\n",
    "\n",
    "1. KeyError is raised when a key is not found in a dictionary or a dictionary-like object. \n",
    "\n",
    "Example - In the example below \"Bangalore\" is not present in the \"dict\" dictionary. Therefore, a \"KeyError\" is raised."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "586fcb75-df0c-4634-b35e-cdc7c9e5b1f1",
   "metadata": {},
   "outputs": [],
   "source": [
    "dict = {\"Delhi\": 1, \"Mumbai\" : 2, \"Chennai\" : 3, \"Kolkata\" : 4}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "fe281543-f511-4762-b7ab-52a516cb60e0",
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'Bangalore'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[7], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;43mdict\u001b[39;49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mBangalore\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m \n",
      "\u001b[0;31mKeyError\u001b[0m: 'Bangalore'"
     ]
    }
   ],
   "source": [
    "dict[\"Bangalore\"] "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a4ce363d-1604-48c7-84cb-fcffb2329a47",
   "metadata": {},
   "source": [
    "2. An IndexError is raised when trying to access an element of a sequence using an index that is out of range. \n",
    "\n",
    "For example: In the example below, \"l\" list contains 5 elements, with indices '0', '1', '2', '3', '4'. Trying to access an element at index '5' is out of range and raises an \"IndexError\"."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "5bc54687-eda4-4c85-8582-91ea15bf1eca",
   "metadata": {},
   "outputs": [],
   "source": [
    "l = [1,2,3,4,5]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "bc4af310-1178-4483-9043-475893256502",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[9], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43ml\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m]\u001b[49m\n",
      "\u001b[0;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "l[5]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5374324b-e563-49ee-a84c-fbd8a278d9b6",
   "metadata": {},
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "27e00a9e-d7cb-4063-a293-a782a4b6426f",
   "metadata": {},
   "source": [
    "Answer 5. ImportError is a built-in Python exception that occurs when there is an error while importing a module. It usually occurs when a required module cannot be found or is not installed properly. This error can be raised when trying to import a module using the import statement or when importing a module using the __import__() function.\n",
    "\n",
    "Example : if a module is not available or does'nt exist, it will throw an ImportError."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "26a139e9-924e-4c0e-a477-9077c18c8028",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'non_existent_module'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[10], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mnon_existent_module\u001b[39;00m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'non_existent_module'"
     ]
    }
   ],
   "source": [
    "import non_existent_module"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9d6416f7-5943-4ce2-94bd-427ff5e901b0",
   "metadata": {},
   "source": [
    "2. ModuleNotFoundError is a subclass of ImportError that was explained in the above example. It is raised when a module cannot be found during an import operation. It is essentially a more specific version of the ImportError that provides more information about the reason for the import failure."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "783984f6-72e8-40cb-9f22-9b6315816b59",
   "metadata": {},
   "source": [
    "Q6. List down some best practices for exception handling in python."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9f926c77-abe8-4d89-ab67-8f0a89dc086a",
   "metadata": {},
   "source": [
    "Answer 6. Exception handling is an important aspect of writing robust and reliable code in Python.\n",
    "\n",
    "Here are some best practices for exception handling in Python:\n",
    "\n",
    "1. Use specific exception types: When catching exceptions, use specific exception types whenever possible, rather than catching the base Exception class. This allows you to handle different types of exceptions differently and can help you diagnose and fix errors more easily.\n",
    "\n",
    "2. Keep exception handling code separate from main logic: Avoid mixing exception handling code with main logic. Instead, handle exceptions in a separate block of code so that it doesn't interfere with the flow of the program.\n",
    "\n",
    "3. Use try-except blocks sparingly: Only use try-except blocks when necessary, and don't use them to handle normal program flow. Overuse of try-except blocks can make your code harder to read and maintain.\n",
    "\n",
    "4. Use finally blocks for cleanup code: If you need to run some code regardless of whether an exception was raised or not, use a finally block to ensure that the cleanup code is always executed.\n",
    "\n",
    "5. Provide useful error messages: When raising exceptions or printing error messages, provide useful information about the error, including the type of the exception, the location of the error, and any relevant information that might help diagnose and fix the error.\n",
    "\n",
    "6. Use logging to record exceptions: Instead of printing exceptions to the console, use a logging framework like the built-in logging module to log exceptions to a file or a remote server. This can help you diagnose and fix errors more easily, especially in large or distributed systems.\n",
    "\n",
    "7. Avoid catching and ignoring exceptions: Catching and ignoring exceptions can hide errors and make debugging more difficult. If you catch an exception, make sure to handle it properly, even if that means logging the error and exiting the program.\n",
    "\n",
    "By following these best practices, we can write more robust and reliable Python code that handles exceptions effectively and provides useful information about errors when they occur.\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9ab12587-8471-4dc3-aea5-c0d04108e6b8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
